scan_body_filter:
  ros__parameters:
    scan_filter_chain:
      - name: body_filter
        type: laser_filters/LaserScanAngularBoundsFilter
        params:
          lower_angle: -2.356  # -135 degrees — rear 90 deg sector removed
          upper_angle:  2.356  #  +135 degrees
